import type { ICategory } from "./types";

//header
export const menuItems = [
  {
    id: 1,
    name: "Services",
    link: "/services",
  },
  {
    id: 2,
    name: "Case Studies",
    link: "/casestudies",
  },
  {
    id: 3,
    name: "About Us",
    link: "/about",
  },
  {
    id: 4,
    name: "Blog",
    link: "/blog",
  },
  {
    id: 5,
    name: "Contacts",
    link: "/contacts",
  },
];

//footer
export const menuItemsFooter = [
  {
    id: 1,
    name: "About Us",
    link: "/about",
  },
  {
    id: 2,
    name: "Case Studies",
    link: "/casestudies",
  },
  {
    id: 3,
    name: "Blog",
    link: "/blog",
  },
  {
    id: 4,
    name: "Careers",
    link: "/careers",
  },
  {
    id: 5,
    name: "Contacts",
    link: "/contacts",
  },
  {
    id: 6,
    name: "Social Media",
    link: "/socialmedia",
  },
  {
    id: 7,
    name: "SEO",
    link: "/seo",
  },
  {
    id: 8,
    name: "Research",
    link: "/research",
  },
  {
    id: 9,
    name: "Content & PR",
    link: "/contentpr",
  },
  {
    id: 10,
    name: "Payed Traffic",
    link: "payedtraffic",
  },
];

//home
export const heroItems = [
  {
    id: 1,
    img: "./image/home/ic-speaker.svg",
    alt: "speaker icon",
    title: "SEO Content Strategy",
  },
  {
    id: 2,
    img: "./image/home/ic-chart.svg",
    alt: "chart icon",
    title: "Content Marketing",
  },
  {
    id: 3,
    img: "./image/home/ic-computer.svg",
    alt: "computer icon",
    title: "Website & Social Media Marketing",
  },
];

export const awards = [
  {
    id: 1,
    image: "./image/home/awards1.png",
    alt: "top SEO Companies 2020 by Clutch award icon",
    text: "Top SEO Companies 2020 by Clutch",
  },
  {
    id: 2,
    image: "./image/home/awards2.png",
    alt: "top Digital Marketing Agency 2019 by UpCity award icon",
    text: "Top Digital Marketing Agency 2019 by UpCity",
  },
  {
    id: 3,
    image: "./image/home/awards3.png",
    alt: "official Member 2020 by Forbes Agency Council award icon",
    text: "Official Member 2020 by Forbes Agency Council",
  },
  {
    id: 4,
    image: "./image/home/awards4.png",
    alt: "top SEO Companies 2020 by Top Developers award icon",
    text: "Top SEO Companies 2020 by Top Developers",
  },
];

export const clients = [
  {
    id: 1,
    image: "./image/home/client-logo1.png",
    alt: "inDepth icon",
  },
  {
    id: 2,
    image: "./image/home/client-logo2.png",
    alt: "hegher fit icon",
  },
  {
    id: 3,
    image: "./image/home/client-logo3.png",
    alt: "sentinal consulting icon",
  },
  {
    id: 4,
    image: "./image/home/client-logo4.png",
    alt: "happy home icon",
  },
  {
    id: 5,
    image: "./image/home/client-logo5.png",
    alt: "orSale icon",
  },
  {
    id: 6,
    image: "./image/home/client-logo7.png",
    alt: "Atlantis Health icon",
  },
  {
    id: 7,
    image: "./image/home/client-logo6.png",
    alt: "sunset realty icon",
  },
  {
    id: 7,
    image: "./image/home/client-logo7.png",
    alt: "Atlantis Health icon",
  },
  {
    id: 8,
    image: "./image/home/client-logo8.png",
    alt: "del Mar icon",
  },
  {
    id: 9,
    image: "./image/home/client-logo9.png",
    alt: "CompleteHealth icon",
  },
  {
    id: 10,
    image: "./image/home/client-logo10.png",
    alt: "National icon",
  },
  {
    id: 11,
    image: "./image/home/client-logo11.png",
    alt: "Ultimate gym icon",
  },
  {
    id: 12,
    image: "./image/home/client-logo12.png",
    alt: "United strategy icon",
  },
];

export const achievements = [
  {
    id: 1,
    image: "./image/home/circle-progress1.png",
    alt: "yellow circle progress",
    text: "Years of experience",
  },
  {
    id: 2,
    image: "./image/home/circle-progress2.png",
    alt: "rose circle progress",
    text: "Awards",
  },
  {
    id: 3,
    image: "./image/home/circle-progress3.png",
    alt: "blue circle progress",
    text: "Projects",
  },
  {
    id: 4,
    image: "./image/home/circle-progress4.png",
    alt: "green circle progress",
    text: "Happy clients",
  },
];

export const askQuestionsItems = [
  {
    id: 1,
    title: "Aliquet lectus urna viverra in odio?",
    text: "Adipiscing nunc arcu enim elit mattis eu placerat proin. Imperdiet elementum faucibus dignissim purus. Fusce parturient diam magna ullamcorper morbi semper massa ac facilisis.",
  },
  {
    id: 2,
    title: "Orci commodo, viverra orci mollis ut euismod?",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos sunt praesentium consequuntur quis, possimus odit! Id doloribus quasi quidem ab labore nemo eos, consequatur aliquam.",
  },
  {
    id: 3,
    title: "Sagittis vitae facilisi rutrum amet mauris quisque vel convallis?",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos sunt praesentium consequuntur quis, possimus odit! Id doloribus quasi quidem ab labore nemo eos, consequatur aliquam.",
  },
  {
    id: 4,
    title: "In id dolor quis nunc, urna hendrerit pharetra?",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos sunt praesentium consequuntur quis, possimus odit! Id doloribus quasi quidem ab labore nemo eos, consequatur aliquam.",
  },
];

export const clientsCaseSliderItems = [
  {
    id: 1,
    logoImg: "./image/home/client-logo.png",
    logoAlt: "National logo",
    title: "Charity organisation",
    text: "Createx SEO Agency helped National Inc. increase their MQL to SQL conversion rate by 300%.",
    circle1: "./image/home/clients-case-orange.png",
    digit1: "90%",
    description1: "Engagement",
    circl2: "./image/home/clients-case-green.png",
    digit2: "100%",
    description2: "Deliverability",
    fon: false,
  },
  {
    id: 2,
    logoImg: "./image/home/clients-case-logo.png",
    logoAlt: "Del Mar logo",
    title: "Oil and natural resources",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Del Mar see a 400% increase in conversion rate..",
    circle1: "./image/home/clients-case-circle-blue.png",
    digit1: "200%",
    description1: "Growth in sales",
    circle2: "./image/home/clients-case-orange-fuul.png",
    digit2: "1,400",
    description2: "Target investors",
    fon: true,
  },
  {
    id: 3,
    logoImg: "./image/home/client-logo7.png",
    logoAlt: "Sunset logo",
    title: "CPersonal care",
    text: "We helped Sunset company break through a noisy industry and better understand their buyer's journey.",
    circle1: "./image/home/clients-case-rose.png",
    digit1: "70%",
    description1: "Open Rate",
    circle2: "./image/home/clients-case-orange-fuul.png",
    digit2: "200%",
    description2: "Growth in sales",
    fon: false,
  },
  {
    id: 4,
    logoImg: "./image/home/client-logo.png",
    logoAlt: "National logo",
    title: "Charity organisation",
    text: "Createx SEO Agency helped National Inc. increase their MQL to SQL conversion rate by 300%.",
    circle1: "./image/home/clients-case-orange.png",
    digit1: "90%",
    description1: "Engagement",
    circle2: "./image/home/clients-case-green.png",
    digit2: "100%",
    description2: "Deliverability",
    fon: false,
  },
  {
    id: 5,
    logoImg: "./image/home/clients-case-logo.png",
    logoAlt: "Del Mar logo",
    title: "Oil and natural resources",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Del Mar see a 400% increase in conversion rate..",
    circle1: "./image/home/clients-case-circle-blue.png",
    digit1: "200%",
    description1: "Growth in sales",
    circle2: "./image/home/clients-case-orange-fuul.png",
    digit2: "1,400",
    description2: "Target investors",
    fon: true,
  },
  {
    id: 6,
    logoImg: "./image/home/client-logo7.png",
    logoAlt: "Sunset logo",
    title: "CPersonal care",
    text: "We helped Sunset company break through a noisy industry and better understand their buyer's journey.",
    circle1: "./image/home/clients-case-rose.png",
    digit1: "70%",
    description1: "Open Rate",
    circle2: "./image/home/clients-case-orange-fuul.png",
    digit2: "200%",
    description2: "Growth in sales",
    fon: false,
  },
];

export const benefits = [
  {
    id: 1,
    image: "./image/home/benefits-ic-speaker.svg",
    altImg: "speaker icon",
    title: "Social Advertising Experts",
    text: "Culpa nostrud commodo ea consequat aliquip reprehenderit. Veniam velit nostrud aliquip sunt.",
  },
  {
    id: 2,
    image: "./image/home/benefits-ic-chat.svg",
    altImg: "chat icon",
    title: "Quality Customer Service",
    text: "Sed nunc scelerisque ipsum accumsan, proin nunc euismod purus. Dictum tortor, pellentesque vel integer amet.",
  },
  {
    id: 3,
    image: "./image/home/benefits-ic-target.svg",
    altImg: "target icon",
    title: "ROI Focused Campaigns",
    text: "Cursus sit eu viverra suspendisse eu quisque enim est tortor. Mauris ornare convallis nisi diam imperdiet.",
  },
  {
    id: 4,
    image: "./image/home/benefits-ic-view.svg",
    altImg: "view icon",
    title: "Complete SEO Transparency",
    text: "Culpa nostrud commodo ea consequat aliquip reprehenderit. Ve niam velit nostrud aliquip sunt.",
  },
  {
    id: 5,
    image: "./image/home/benefits-ic-checklist.svg",
    altImg: "checklist icon",
    title: "Monthly Reporting",
    text: "Aenean urna dictum adipiscing nec, cras quisque. Nunc in odio ultricies ornare ornare nunc venenatis mauris.",
  },
  {
    id: 6,
    image: "./image/home/benefits-ic-like.svg",
    altImg: "like icon",
    title: "We're a True Partner",
    text: "Quis sed malesuada tincidunt amet, vitae mi justo elementum eu. Dui gravida id elementum dolor sed elementum, risus.",
  },
];

export const pricingPlans = [
  {
    id: 1,
    tarif: "Basic",
    price: 24,
    dopclass: "",
  },
  {
    id: 2,
    tarif: "Optimal",
    price: 64,
    dopclass: "black",
  },
  {
    id: 3,
    tarif: "Premium",
    price: 98,
    dopclass: "",
  },
];

export const feedbackSliderItems = [
  {
    id: 1,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo, amet lectus quam viverra mus lobortis fermentum amet, eu. Pulvinar eu sed purus facilisi. Vitae id turpis tempus ornare turpis quis non. Congue tortor in euismod vulputate etiam eros. Pulvinar neque pharetra arcu diam maecenas diam integer in.",
    image: "./image/home/slider-foto.png",
    alt: "clients foto",
    name: "Courtney Alexander",
    position: "Position, Company name",
  },
  {
    id: 2,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo, amet lectus quam viverra mus lobortis fermentum amet, eu. Pulvinar eu sed purus facilisi. Vitae id turpis tempus ornare turpis quis non. Congue tortor in euismod vulputate etiam eros. Pulvinar neque pharetra arcu diam maecenas diam integer in.",
    image: "./image/home/slider-foto.png",
    alt: "clients foto",
    name: "Courtney Alexander",
    position: "Position, Company name",
  },
  {
    id: 3,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo, amet lectus quam viverra mus lobortis fermentum amet, eu. Pulvinar eu sed purus facilisi. Vitae id turpis tempus ornare turpis quis non. Congue tortor in euismod vulputate etiam eros. Pulvinar neque pharetra arcu diam maecenas diam integer in.",
    image: "./image/home/slider-foto.png",
    alt: "clients foto",
    name: "Courtney Alexander",
    position: "Position, Company name",
  },
  {
    id: 4,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo, amet lectus quam viverra mus lobortis fermentum amet, eu. Pulvinar eu sed purus facilisi. Vitae id turpis tempus ornare turpis quis non. Congue tortor in euismod vulputate etiam eros. Pulvinar neque pharetra arcu diam maecenas diam integer in.",
    image: "./image/home/slider-foto.png",
    alt: "clients foto",
    name: "Courtney Alexander",
    position: "Position, Company name",
  },
  {
    id: 5,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo, amet lectus quam viverra mus lobortis fermentum amet, eu. Pulvinar eu sed purus facilisi. Vitae id turpis tempus ornare turpis quis non. Congue tortor in euismod vulputate etiam eros. Pulvinar neque pharetra arcu diam maecenas diam integer in.",
    image: "./image/home/slider-foto.png",
    alt: "clients foto",
    name: "Courtney Alexander",
    position: "Position, Company name",
  },
  {
    id: 6,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Justo, amet lectus quam viverra mus lobortis fermentum amet, eu. Pulvinar eu sed purus facilisi. Vitae id turpis tempus ornare turpis quis non. Congue tortor in euismod vulputate etiam eros. Pulvinar neque pharetra arcu diam maecenas diam integer in.",
    image: "./image/home/slider-foto.png",
    alt: "clients foto",
    name: "Courtney Alexander",
    position: "Position, Company name",
  },
];

export const homeNews = [
  {
    id: 1,
    image: "./image/home/news1.png",
    alt: "news picture",
    category: "SEO",
    date: "July 5, 2020",
    autor: "Diane Mccoy",
    title: "How to Maximize Your ROI Through Scientific SEM?",
    text: "Vulputate vitae pellentesque scelerisque luctus consequat mattis pellentesque dui odio...",
  },
  {
    id: 2,
    image: "./image/home/news2.png",
    alt: "news picture",
    category: "Marketing",
    date: "July 5, 2020",
    autor: "Diane Mccoy",
    title: "The Basics of Blogging Search Engine Optimization.",
    text: "Mauris tincidunt sollicitudin tristique odio eget volutpat. Fringilla viverra amet, mi interdum blandit...",
  },
];

export const servicesBlockInfo = [
  {
    id: 1,
    title: "Social Media Marketing",
    text: "Eleifend orci massa et facilisis orci feugiat ac. Congue in ut lacus, turpis accumsan gravida. Aliquet mattis dignissim massa sociis a, id bibendum. Egestas lorem eros, mi cras amet, vel eget molestie. Turpis enim arcu, amet donec massa pellentesque nulla duis. Arcu dictum metus sed purus senectus faucibus eget elementum pretium. ",
    image: "./image/services/marketing-mainimg.png",
    classDop: "marketing",
  },
  {
    id: 2,
    title: "Search Engine Optimization",
    text: "Elementum ipsum lorem tortor morbi quis turpis pellentesque ultrices aenean. Lacus sit viverra et egestas nisl vitae lacus, eget. Eu pulvinar duis in posuere non adipiscing. Nunc, tristique viverra tincidunt nec proin tempus egestas massa. Quis velit nunc nisl sem in tristique.",
    image: "./image/services/optimization-mainimg.png",
    classDop: "optimization",
  },
  {
    id: 3,
    title: "Research Service",
    text: "Volutpat tellus mauris sit sit. Posuere ut sit vestibulum amet viverra in. Est nulla lectus purus tincidunt massa tortor. Hendrerit vulputate elementum blandit massa vitae amet felis eget.",
    image: "./image/services/research-mainimg.png",
    classDop: "research",
  },
  {
    id: 4,
    title: "Content & PR Service",
    text: "Consequat pharetra elit posuere fringilla luctus sit. Curabitur accumsan fermentum magna amet. Sed nec amet posuere tellus pellentesque vitae. Pulvinar nulla sem risus diam volutpat. Amet, sit aliquet magna in viverra at elit nullam.",
    image: "./image/services/content-mainimg.png",
    classDop: "content",
  },
  {
    id: 5,
    title: "Payed Traffic Management",
    text: "Tortor vitae orci hendrerit lobortis eu. Metus aliquam sem tellus ut fringilla purus nisl, consectetur netus. Velit ac feugiat ut mattis dis nullam ultrices amet. Lacus eu neque arcu arcu curabitur at sapien. Id sed aliquet id sit nibh ornare massa scelerisque.",
    image: "./image/services/management-mainimg.png",
    classDop: "management",
  },
];

export const markets = [
  {
    id: 1,
    image: "./image/services/markets-ic-cart.svg",
    alt: "cart icon",
    title: "E-commerce Websites",
    text: "Aenean urna dictum adipiscing nec, cras quisque. Nunc in mauris.",
  },
  {
    id: 2,
    image: "./image/services/markets-ic-website.svg",
    alt: "website icon",
    title: "Content-rich Websites",
    text: "Culpa nostrud commodo ea consequat reprehenderit aliquip.",
  },
  {
    id: 3,
    image: "./image/services/markets-ic-suitcase.svg",
    alt: "suitcase icon",
    title: "B2B /B2C Services",
    text: "Viverra scelerisque consequat net. Adipisicing esse consequat.",
  },
  {
    id: 4,
    image: "./image/services/markets-ic-startup.svg",
    alt: "startup icon",
    title: "Startup Projects",
    text: "Aute eiusmod dolore dolore deserunt veniam ad deserunt.",
  },
];

export const caseCardsFilter = [
  {
    id: 1,
    name: "All case studies",
  },
  {
    id: 2,
    name: "Social Media",
  },
  {
    id: 3,
    name: "SEO",
  },
  {
    id: 4,
    name: "Research",
  },
  {
    id: 5,
    name: "Content & PR",
  },
  {
    id: 6,
    name: "Payed Traffic",
  },
];

export const caseCards = [
  {
    id: 1,
    imgmain: "./image/casestudies/case-card1.png",
    altmain: "Charity organisation",
    imglogo: "./image/casestudies/client-logo1.svg",
    altlogo: "National logo",
    title: "Charity organisation",
    circle1: "./image/casestudies/case-circle-orange.png",
    circle2: "./image/casestudies/case-circle-green.png",
    digit1: "90%",
    digit2: "100%",
    description1: "Engagement",
    description2: "Deliverability",
    text: "Createx SEO Agency helped JNational Inc. increase their MQL to SQL conversion rate by 300%.",
    category: 6,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "The Company has been with us for 3 months. They are in our optimal package for SEO & our premium package for SEM plus Ad spend ($1,000). The client’s goal was toget growth in sales. We helped exceeding the client’s goals in generating new clients.",
      },
      {
        id: 2,
        type: "simple_text",
        text: "At facilisi sapien posuere eget nunc senectus proin nullam. Tortor senectus in et sagittis, vitae diam cras dignissim. Varius adipiscing eget diam nisi. Orci, consectetur vulputate metus ornare pharetra, neque, fermentum. Vel nec rhoncus, non nunc, neque in massa. Feugiat leo nam nisl lacinia amet, odio. Mi varius viverra risus vel.",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/diagram.png",
        altImg: "diagram",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Gravida elit et libero, varius congue risus quisque enim.",
          "Sit quis vitae, gravida aliquam condimentum.",
          "Praesent et facilisis nam mus senectus massa dignissim.",
          "Fermentum diam elementum viverra proin.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Enim, vel massa odio diam. Blandit massa gravida feugiat elementum id nec sed leo. Nisi in ornare lectus eget. Urna, risus, consectetur volutpat lorem purus. Velit aliquet nibh vitae maecenas. Consectetur neque ut aliquam eros, purus enim dignissim aenean vitae. Ultrices fames augue mattis tortor est justo, pharetra nibh risus. Facilisi at porttitor volutpat natoque proin amet, nulla. Vivamus ut lobortis sagittis curabitur tellus convallis eget netus vitae.",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/illustration-item.png",
        altImg: "many diagrams",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Mauris dignissim blandit cursus imperdiet accumsan lorem vel, tortor.",
          "Quis mauris vel felis convallis nulla dignissim.",
          "Cursus sit platea ac posuere non interdum in.",
          "Mattis pellentesque vel, venenatis, urna, quis ut.",
        ],
      },
    ],
  },
  {
    id: 2,
    imgmain: "./image/casestudies/case-card2.png",
    altmain: "Oil and natural resources",
    imglogo: "./image/casestudies/client-logo2.svg",
    altlogo: "Del Mar Strategy logo",
    title: "Oil and natural resources",
    circle1: "./image/casestudies/case-circle-blue-full.png",
    circle2: "./image/casestudies/case-circle-orange.png",
    digit1: "200%",
    digit2: "1,400",
    description1: "Growth in sales",
    description2: "Target investors",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Del Mar see a 400% increase in conversion rate.",
    category: 6,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card2.png",
        altImg: "Del Mar Strategy",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 7,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 3,
    imgmain: "./image/casestudies/case-card3.png",
    altmain: "Electric company",
    imglogo: "./image/casestudies/client-logo3.svg",
    altlogo: "For Sale logo",
    title: "Electric company",
    circle1: "./image/casestudies/case-circle-rose.png",
    circle2: "./image/casestudies/case-circle-blue-full.png",
    digit1: "80%",
    digit2: "1,840",
    description1: "Open Rate",
    description2: "Target investors",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Lovato see a 200% increase in conversion rate.",
    category: 4,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card3.png",
        altImg: "Electric company",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/illustration-item.png",
        altImg: "many diagrams",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 4,
    imgmain: "./image/casestudies/case-card4.png",
    altmain: "Personal care",
    imglogo: "./image/casestudies/client-logo4.svg",
    altlogo: "Sanset Realty logo",
    title: "Personal care",
    circle1: "./image/casestudies/case-circle-rose.png",
    circle2: "./image/casestudies/case-circle-orange-full.png",
    digit1: "70%",
    digit2: "200%",
    description1: "Open Rate",
    description2: "Growth in sales",
    text: "We helped Sunset company break through a noisy industry and better understand their buyer's journey.",
    category: 2,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/diagram.png",
        altImg: "diagram",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card4.png",
        altImg: "Personal care",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 5,
    imgmain: "./image/casestudies/case-card5.png",
    altmain: "Departments stores",
    imglogo: "./image/casestudies/client-logo5.svg",
    altlogo: "Higher Fit logo",
    title: "Departments stores",
    circle1: "./image/casestudies/case-circle-blue.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "70%",
    digit2: "190+",
    description1: "Increase in leads",
    description2: "Prospects",
    text: "We helped Dove company break through a noisy industry and better understand their buyer's journey.",
    category: 6,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card5.png",
        altImg: "Departments stores",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card4.png",
        altImg: "Personal care",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 6,
    imgmain: "./image/casestudies/case-card6.png",
    altmain: "Electric cars, solar & clean energy",
    imglogo: "./image/casestudies/client-logo6.svg",
    altlogo: "Sential Consulting",
    title: "Electric cars, solar & clean energy",
    circle1: "./image/casestudies/case-circle-green.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "200%",
    digit2: "$12,000",
    description1: "ROI",
    description2: "Increase per month",
    text: "We helped Dove company break through a noisy industry and better understand their buyer's journey.",
    category: 6,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card5.png",
        altImg: "Departments stores",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card6.png",
        altImg: "Electric cars, solar & clean energy",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 7,
    imgmain: "./image/casestudies/case-card1.png",
    altmain: "Charity organisation",
    imglogo: "./image/casestudies/client-logo1.svg",
    altlogo: "National logo",
    title: "Charity organisation",
    circle1: "./image/casestudies/case-circle-orange.png",
    circle2: "./image/casestudies/case-circle-green.png",
    digit1: "90%",
    digit2: "100%",
    description1: "Engagement",
    description2: "Deliverability",
    text: "Createx SEO Agency helped JNational Inc. increase their MQL to SQL conversion rate by 300%.",
    category: 3,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "The Company has been with us for 3 months. They are in our optimal package for SEO & our premium package for SEM plus Ad spend ($1,000). The client’s goal was toget growth in sales. We helped exceeding the client’s goals in generating new clients.",
      },
      {
        id: 2,
        type: "simple_text",
        text: "At facilisi sapien posuere eget nunc senectus proin nullam. Tortor senectus in et sagittis, vitae diam cras dignissim. Varius adipiscing eget diam nisi. Orci, consectetur vulputate metus ornare pharetra, neque, fermentum. Vel nec rhoncus, non nunc, neque in massa. Feugiat leo nam nisl lacinia amet, odio. Mi varius viverra risus vel.",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/diagram.png",
        altImg: "diagram",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Gravida elit et libero, varius congue risus quisque enim.",
          "Sit quis vitae, gravida aliquam condimentum.",
          "Praesent et facilisis nam mus senectus massa dignissim.",
          "Fermentum diam elementum viverra proin.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Enim, vel massa odio diam. Blandit massa gravida feugiat elementum id nec sed leo. Nisi in ornare lectus eget. Urna, risus, consectetur volutpat lorem purus. Velit aliquet nibh vitae maecenas. Consectetur neque ut aliquam eros, purus enim dignissim aenean vitae. Ultrices fames augue mattis tortor est justo, pharetra nibh risus. Facilisi at porttitor volutpat natoque proin amet, nulla. Vivamus ut lobortis sagittis curabitur tellus convallis eget netus vitae.",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/illustration-item.png",
        altImg: "many diagrams",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Mauris dignissim blandit cursus imperdiet accumsan lorem vel, tortor.",
          "Quis mauris vel felis convallis nulla dignissim.",
          "Cursus sit platea ac posuere non interdum in.",
          "Mattis pellentesque vel, venenatis, urna, quis ut.",
        ],
      },
    ],
  },
  {
    id: 8,
    imgmain: "./image/casestudies/case-card2.png",
    altmain: "Oil and natural resources",
    imglogo: "./image/casestudies/client-logo2.svg",
    altlogo: "Del Mar Strategy logo",
    title: "Charity organisation",
    circle1: "./image/casestudies/case-circle-blue-full.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "200%",
    digit2: "1,400",
    description1: "Growth in sales",
    description2: "Target investors",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Del Mar see a 400% increase in conversion rate.",
    category: 5,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card2.png",
        altImg: "Del Mar Strategy",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 7,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 9,
    imgmain: "./image/casestudies/case-card3.png",
    altmain: "Electric company",
    imglogo: "./image/casestudies/client-logo1.svg",
    altlogo: "For Sale logo",
    title: "Electric company",
    circle1: "./image/casestudies/case-circle-rose.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "80%",
    digit2: "1,840",
    description1: "Open Rate",
    description2: "Target investors",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Lovato see a 200% increase in conversion rate.",
    category: 5,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card3.png",
        altImg: "Electric company",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/illustration-item.png",
        altImg: "many diagrams",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 10,
    imgmain: "./image/casestudies/case-card4.png",
    altmain: "Personal care",
    imglogo: "./image/casestudies/client-logo4.svg",
    altlogo: "Sanset Realty logo",
    title: "Personal care",
    circle1: "./image/casestudies/case-circle-rose.png",
    circle2: "./image/casestudies/case-circle-orange-full.png",
    digit1: "70%",
    digit2: "200%",
    description1: "Open Rate",
    description2: "Growth in sales",
    text: "We helped Sunset company break through a noisy industry and better understand their buyer's journey.",
    category: 2,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/diagram.png",
        altImg: "diagram",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card4.png",
        altImg: "Personal care",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 11,
    imgmain: "./image/casestudies/case-card5.png",
    altmain: "Departments stores",
    imglogo: "./image/casestudies/client-logo5.svg",
    altlogo: "Higher Fit logo",
    title: "Departments stores",
    circle1: "./image/casestudies/case-circle-blue.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "70%",
    digit2: "190+",
    description1: "Increase in leads",
    description2: "Prospects",
    text: "We helped Dove company break through a noisy industry and better understand their buyer's journey.",
    category: 6,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card5.png",
        altImg: "Departments stores",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card4.png",
        altImg: "Personal care",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 12,
    imgmain: "./image/casestudies/case-card6.png",
    altmain: "Electric cars, solar & clean energy",
    imglogo: "./image/casestudies/client-logo6.svg",
    altlogo: "Sential Consulting",
    title: "Electric cars, solar & clean energy",
    circle1: "./image/casestudies/case-circle-green.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "200%",
    digit2: "$12,000",
    description1: "ROI",
    description2: "Increase per month",
    text: "We helped Dove company break through a noisy industry and better understand their buyer's journey.",
    category: 6,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card5.png",
        altImg: "Departments stores",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card6.png",
        altImg: "Electric cars, solar & clean energy",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 13,
    imgmain: "./image/casestudies/case-card1.png",
    altmain: "Charity organisation",
    imglogo: "./image/casestudies/client-logo1.svg",
    altlogo: "National logo",
    title: "Charity organisation",
    circle1: "./image/casestudies/case-circle-orange.png",
    circle2: "./image/casestudies/case-circle-green.png",
    digit1: "90%",
    digit2: "100%",
    description1: "Engagement",
    description2: "Deliverability",
    text: "Createx SEO Agency helped JNational Inc. increase their MQL to SQL conversion rate by 300%.",
    category: 3,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "The Company has been with us for 3 months. They are in our optimal package for SEO & our premium package for SEM plus Ad spend ($1,000). The client’s goal was toget growth in sales. We helped exceeding the client’s goals in generating new clients.",
      },
      {
        id: 2,
        type: "simple_text",
        text: "At facilisi sapien posuere eget nunc senectus proin nullam. Tortor senectus in et sagittis, vitae diam cras dignissim. Varius adipiscing eget diam nisi. Orci, consectetur vulputate metus ornare pharetra, neque, fermentum. Vel nec rhoncus, non nunc, neque in massa. Feugiat leo nam nisl lacinia amet, odio. Mi varius viverra risus vel.",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/diagram.png",
        altImg: "diagram",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Gravida elit et libero, varius congue risus quisque enim.",
          "Sit quis vitae, gravida aliquam condimentum.",
          "Praesent et facilisis nam mus senectus massa dignissim.",
          "Fermentum diam elementum viverra proin.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Enim, vel massa odio diam. Blandit massa gravida feugiat elementum id nec sed leo. Nisi in ornare lectus eget. Urna, risus, consectetur volutpat lorem purus. Velit aliquet nibh vitae maecenas. Consectetur neque ut aliquam eros, purus enim dignissim aenean vitae. Ultrices fames augue mattis tortor est justo, pharetra nibh risus. Facilisi at porttitor volutpat natoque proin amet, nulla. Vivamus ut lobortis sagittis curabitur tellus convallis eget netus vitae.",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/illustration-item.png",
        altImg: "many diagrams",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Mauris dignissim blandit cursus imperdiet accumsan lorem vel, tortor.",
          "Quis mauris vel felis convallis nulla dignissim.",
          "Cursus sit platea ac posuere non interdum in.",
          "Mattis pellentesque vel, venenatis, urna, quis ut.",
        ],
      },
    ],
  },
  {
    id: 14,
    imgmain: "./image/casestudies/case-card2.png",
    altmain: "Oil and natural resources",
    imglogo: "./image/casestudies/client-logo2.svg",
    altlogo: "Del Mar Strategy logo",
    title: "Charity organisation",
    circle1: "./image/casestudies/case-circle-blue-full.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "200%",
    digit2: "1,400",
    description1: "Growth in sales",
    description2: "Target investors",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Del Mar see a 400% increase in conversion rate.",
    category: 5,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card2.png",
        altImg: "Del Mar Strategy",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 7,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 15,
    imgmain: "./image/casestudies/case-card3.png",
    altmain: "Electric company",
    imglogo: "./image/casestudies/client-logo1.svg",
    altlogo: "For Sale logo",
    title: "Electric company",
    circle1: "./image/casestudies/case-circle-rose.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "80%",
    digit2: "1,840",
    description1: "Open Rate",
    description2: "Target investors",
    text: "With an advanced A/B testing and usability analysis, Createx SEO Agency helps Lovato see a 200% increase in conversion rate.",
    category: 4,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card3.png",
        altImg: "Electric company",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/illustration-item.png",
        altImg: "many diagrams",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 16,
    imgmain: "./image/casestudies/case-card4.png",
    altmain: "Personal care",
    imglogo: "./image/casestudies/client-logo4.svg",
    altlogo: "Sanset Realty logo",
    title: "Personal care",
    circle1: "./image/casestudies/case-circle-rose.png",
    circle2: "./image/casestudies/case-circle-orange-full.png",
    digit1: "70%",
    digit2: "200%",
    description1: "Open Rate",
    description2: "Growth in sales",
    text: "We helped Sunset company break through a noisy industry and better understand their buyer's journey.",
    category: 2,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/diagram.png",
        altImg: "diagram",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card4.png",
        altImg: "Personal care",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 17,
    imgmain: "./image/casestudies/case-card5.png",
    altmain: "Departments stores",
    imglogo: "./image/casestudies/client-logo5.svg",
    altlogo: "Higher Fit logo",
    title: "Departments stores",
    circle1: "./image/casestudies/case-circle-blue.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "70%",
    digit2: "190+",
    description1: "Increase in leads",
    description2: "Prospects",
    text: "We helped Dove company break through a noisy industry and better understand their buyer's journey.",
    category: 6,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card5.png",
        altImg: "Departments stores",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card4.png",
        altImg: "Personal care",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
  {
    id: 18,
    imgmain: "./image/casestudies/case-card6.png",
    altmain: "Electric cars, solar & clean energy",
    imglogo: "./image/casestudies/client-logo6.svg",
    altlogo: "Sential Consulting",
    title: "Electric cars, solar & clean energy",
    circle1: "./image/casestudies/case-circle-green.png",
    circle2: "./image/casestudies/case-circle-rose.png",
    digit1: "200%",
    digit2: "$12,000",
    description1: "ROI",
    description2: "Increase per month",
    text: "We helped Dove company break through a noisy industry and better understand their buyer's journey.",
    category: 5,
    blocks: [
      {
        id: 1,
        type: "rich_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 2,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 3,
        type: "gallery",
        img: "./image/casestudies/case-card5.png",
        altImg: "Departments stores",
      },
      {
        id: 4,
        type: "list",
        title: "Strategies",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
      {
        id: 5,
        type: "simple_text",
        text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maxime ipsum modi blanditiis aspernatur explicabo eveniet, possimus quae tempora molestias, incidunt corporis dicta sequi quo dolorem, accusantium praesentium? Vel, tenetur cum!",
      },
      {
        id: 6,
        type: "gallery",
        img: "./image/casestudies/case-card6.png",
        altImg: "Electric cars, solar & clean energy",
      },
      {
        id: 7,
        type: "list",
        title: "Resieved goals",
        listItems: [
          "Bibendum malesuada mauris, id nisl enim diam.",
          "Nam id in non sed cras purus nunc et.",
          "Neque tortor, pellentesque amet est, eu accumsan condimentum nulla.",
          "Mauris orci, cursus nisl odio est adipiscing gravida magna eget.",
          "Sit turpis sit ultrices viverra adipiscing malesuada.",
        ],
      },
      {
        id: 8,
        type: "list",
        title: "Results",
        listItems: [
          "Lorem ipsum dolor sit, amet consectetur.",
          "Maxime ipsum modi blanditiis aspernatur.",
          "Possimus quae tempora molestias.",
          "Incidunt corporis dicta sequi quo dolorem.",
        ],
      },
    ],
  },
];

//About Us

export const coreValuesItems = [
  {
    id: 1,
    image: "./image/about/core-ic-like.svg",
    alt: "like icon",
    title: "Respect",
    text: "Odio posuere netus quisque faucibus lectus arcu donec. Eget dictum eu viverra faucibus. Viverra scelerisque consequat.",
  },
  {
    id: 2,
    image: "./image/about/core-ic-view.svg",
    alt: "view icon",
    title: "Transparency",
    text: "Adipiscing nunc arcu enim elit mattis eu placerat proin. Imperdiet elementum faucibus dignissim purus.",
  },
  {
    id: 3,
    image: "./image/about/core-ic-checklist.svg",
    alt: "checklist icon",
    title: "Commitment",
    text: "Fusce parturient diam magna ullamcorper morbi semper massa ac facilisisViverra scelerisque consequat.",
  },
  {
    id: 4,
    image: "./image/about/core-ic-management.svg",
    alt: "management icon",
    title: "Cooperation",
    text: "Porttitor diam consectetur aliquam vitae urna, pharetra, at ipsum. Pretium placerat turpis sed viverra consequat.",
  },
];

export const team = [
  {
    id: 1,
    img: "./image/about/team1.png",
    alt: "Courtney Alexander foto",
    name: "Courtney Alexander",
    position: "Founder and CEO",
  },
  {
    id: 2,
    img: "./image/about/team2.png",
    alt: "Johnny Lane foto",
    name: "Johnny Lane",
    position: "Director of Client Services",
  },
  {
    id: 3,
    img: "./image/about/team3.png",
    alt: "Diane Mccoy foto",
    name: "Diane Mccoy",
    position: "Lead Digital PR Strategist",
  },
  {
    id: 4,
    img: "./image/about/team4.png",
    alt: "Judith Warren foto",
    name: "Judith Warren",
    position: "Cheaf Marketing Officer",
  },
  {
    id: 5,
    img: "./image/about/team5.png",
    alt: "Floyd Simmmons foto",
    name: "Floyd Simmmons",
    position: "Account Director",
  },
  {
    id: 6,
    img: "./image/about/team6.png",
    alt: "Shawn Edwards foto",
    name: "Shawn Edwards",
    position: "Director of PPC",
  },
  {
    id: 7,
    img: "./image/about/team7.png",
    alt: "Jane Cooper foto",
    name: "Jane Cooper",
    position: "Digital Marketing Manager",
  },
  {
    id: 8,
    img: "./image/about/team8.png",
    alt: "Soham Alexander foto",
    name: "Soham Alexander",
    position: "Director of SEO",
  },
];

//contacts

export const contactsHeroCards = [
  {
    id: 1,
    image: "./image/contacts/hero-outline-icon.svg",
    alt: "outline-icon",
    title: "Visit us",
    text1: "2464 Royal Ln. Mesa,",
    text2: "New Jersey 45463, USA",
    link: "See on the map",
  },
  {
    id: 2,
    image: "./image/contacts/hero-phone-icon.svg",
    alt: "phone-icon",
    title: "Call us",
    text1: "(405) 555-0128",
    text2: "(603) 555-0123",
  },
  {
    id: 3,
    image: "./image/contacts/hero-chat-icon.svg",
    alt: "chat-icon",
    title: "Talk to us",
    text1: "hello@createx.com",
  },
  {
    id: 4,
    image: "./image/contacts/hero-clock-icon.svg",
    alt: "clock-icon",
    title: "Working Hours",
    text1: "Mon-Fri: 9 am — 6 pm",
    text2: "Sat-Sun: days off",
  },
];

export const contactsRadioButtons = [
  {
    id: 1,
    value: "service1",
    name: "Social Media",
  },
  {
    id: 2,
    value: "service2",
    name: "SEO",
  },
  {
    id: 3,
    value: "service3",
    name: "Research",
  },
  {
    id: 4,
    value: "service4",
    name: "Content & PR",
  },
  {
    id: 5,
    value: "service5",
    name: "Payed Traffic",
  },
];

export const contactsFormFields = [
  {
    id: 1,
    label: "First Name*",
    fieldType: "text",
    text: "Your first name",
    isRequired: true,
  },
  {
    id: 2,
    label: "Last Name*",
    fieldType: "text",
    text: "Your last name",
    isRequired: true,
  },
  {
    id: 3,
    label: "Email*",
    fieldType: "email",
    text: "Your working email",
    isRequired: true,
  },
  {
    id: 4,
    label: "Phone*",
    fieldType: "tel",
    text: "Your phone number",
    isRequired: true,
  },
  {
    id: 5,
    label: "Company",
    fieldType: "text",
    text: "Your company name",
    isRequired: false,
  },
  {
    id: 6,
    label: "Position",
    fieldType: "text",
    text: "Your position",
    isRequired: false,
  },
];

//blog
export const posts = [
  {
    id: 1,
    img: "./image/blog/latest-post1.png",
    alt: "someone is writing something in a notebook",
    category: 4,
    date: "07.07.2021",
    autor: "By Diane Mccoy",
    title: "How to Maximize Your ROI Through Scientific SEM?",
    text: "",
  },
  {
    id: 2,
    img: "./image/blog/latest-post2.png",
    alt: "a hand with a pen on a diagram",
    category: 3,
    date: "06.07.2021",
    autor: "By Diane Mccoy",
    title: "The Basics of Blogging Search Engine Optimization.",
    text: "",
  },
  {
    id: 3,
    img: "./image/blog/post1.png",
    alt: "three-dimensional multi-colored parts of a pie chart",
    category: 3,
    date: "12.06.2020",
    autor: "By Soham Alexander",
    title: "Digital Marketing Game: What You Need to Know to Stay Ahead?",
    text: "Nunc nulla vestibulum nunc quam arcu tristique convallis. Posuere augue pellentesque mauris gravida",
  },
  {
    id: 4,
    img: "./image/blog/post2.png",
    alt: "colorful cubes with pictures are on the keyboard",
    category: 2,
    date: "06.06.2020",
    autor: "By Shawn Edwards",
    title: "How to Evaluate and Compare Social Media Tools Today.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 5,
    img: "./image/blog/post3.png",
    alt: "cubes with arrows",
    category: 4,
    date: "01.05.2020",
    autor: "By Shawn Edwards",
    title: "The Best Practices to Optimize Your Website for Mobile.",
    text: "Pharetra, ullamcorper iaculis viverra parturient sed id sed. Convallis proin dignissim lacus, purus gravida",
  },
  {
    id: 6,
    img: "./image/blog/post4.png",
    alt: "the index finger points to the search bar",
    category: 5,
    date: "25.04.2020",
    autor: "By Diane Mccoy",
    title: "10 Seriously Underused Paid Search Strategies.",
    text: "Euismod congue faucibus diam etiam diam netus vitae ornare vitae. Cursus sollicitudin posuere venenatis",
  },
  {
    id: 7,
    img: "./image/blog/post5.png",
    alt: "an open book with an inscription -  Content is King",
    category: 1,
    date: "03.06.2020",
    autor: "By Shawn Edwards",
    title: "How to Create Content That Gets Linked and Shared.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 8,
    img: "./image/blog/post6.png",
    alt: "a head from which light bulbs fly up",
    category: 2,
    date: "18.03.2020",
    autor: "By Jane Cooper",
    title: "12 Simple Tips to Creating an Effective Ad.",
    text: "Imperdiet risus consectetur dignissim lorem sollicitudin eget bibendum pellentesque nec. Adipiscing viverra in non euismod. Amet nulla aliquam nulla magna",
  },
  {
    id: 9,
    img: "./image/blog/post1.png",
    alt: "three-dimensional multi-colored parts of a pie chart",
    category: 3,
    date: "12.06.2019",
    autor: "By Soham Alexander",
    title: "Digital Marketing Game: What You Need to Know to Stay Ahead?",
    text: "Nunc nulla vestibulum nunc quam arcu tristique convallis. Posuere augue pellentesque mauris gravida",
  },
  {
    id: 10,
    img: "./image/blog/post2.png",
    alt: "colorful cubes with pictures are on the keyboard",
    category: 2,
    date: "06.06.2019",
    autor: "By Shawn Edwards",
    title: "How to Evaluate and Compare Social Media Tools Today.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 11,
    img: "./image/blog/post3.png",
    alt: "cubes with arrows",
    category: 4,
    date: "01.05.2019",
    autor: "By Shawn Edwards",
    title: "The Best Practices to Optimize Your Website for Mobile.",
    text: "Pharetra, ullamcorper iaculis viverra parturient sed id sed. Convallis proin dignissim lacus, purus gravida",
  },
  {
    id: 12,
    img: "./image/blog/post4.png",
    alt: "the index finger points to the search bar",
    category: 5,
    date: "25.04.2019",
    autor: "By Diane Mccoy",
    title: "10 Seriously Underused Paid Search Strategies.",
    text: "Euismod congue faucibus diam etiam diam netus vitae ornare vitae. Cursus sollicitudin posuere venenatis",
  },
  {
    id: 13,
    img: "./image/blog/post5.png",
    alt: "an open book with an inscription -  Content is King",
    category: 1,
    date: "03.06.2019",
    autor: "By Shawn Edwards",
    title: "How to Create Content That Gets Linked and Shared.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 14,
    img: "./image/blog/post6.png",
    alt: "a head from which light bulbs fly up",
    category: 2,
    date: "18.03.2019",
    autor: "By Jane Cooper",
    title: "12 Simple Tips to Creating an Effective Ad.",
    text: "Imperdiet risus consectetur dignissim lorem sollicitudin eget bibendum pellentesque nec. Adipiscing viverra in non euismod. Amet nulla aliquam nulla magna",
  },
  {
    id: 15,
    img: "./image/blog/post1.png",
    alt: "three-dimensional multi-colored parts of a pie chart",
    category: 3,
    date: "12.03.2018",
    autor: "By Soham Alexander",
    title: "Digital Marketing Game: What You Need to Know to Stay Ahead?",
    text: "Nunc nulla vestibulum nunc quam arcu tristique convallis. Posuere augue pellentesque mauris gravida",
  },
  {
    id: 16,
    img: "./image/blog/post2.png",
    alt: "colorful cubes with pictures are on the keyboard",
    category: 2,
    date: "06.03.2018",
    autor: "By Shawn Edwards",
    title: "How to Evaluate and Compare Social Media Tools Today.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 17,
    img: "./image/blog/post3.png",
    alt: "cubes with arrows",
    category: 4,
    date: "01.03.2018",
    autor: "By Shawn Edwards",
    title: "The Best Practices to Optimize Your Website for Mobile.",
    text: "Pharetra, ullamcorper iaculis viverra parturient sed id sed. Convallis proin dignissim lacus, purus gravida",
  },
  {
    id: 18,
    img: "./image/blog/post4.png",
    alt: "the index finger points to the search bar",
    category: 5,
    date: "25.02.2018",
    autor: "By Diane Mccoy",
    title: "10 Seriously Underused Paid Search Strategies.",
    text: "Euismod congue faucibus diam etiam diam netus vitae ornare vitae. Cursus sollicitudin posuere venenatis",
  },
  {
    id: 19,
    img: "./image/blog/post5.png",
    alt: "an open book with an inscription -  Content is King",
    category: 1,
    date: "23.02.2018",
    autor: "By Shawn Edwards",
    title: "How to Create Content That Gets Linked and Shared.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 20,
    img: "./image/blog/post6.png",
    alt: "a head from which light bulbs fly up",
    category: 2,
    date: "18.02.2018",
    autor: "By Jane Cooper",
    title: "12 Simple Tips to Creating an Effective Ad.",
    text: "Imperdiet risus consectetur dignissim lorem sollicitudin eget bibendum pellentesque nec. Adipiscing viverra in non euismod. Amet nulla aliquam nulla magna",
    trend: false,
  },
  {
    id: 21,
    img: "./image/blog/post1.png",
    alt: "three-dimensional multi-colored parts of a pie chart",
    category: 3,
    date: "12.02.2017",
    autor: "By Soham Alexander",
    title: "Digital Marketing Game: What You Need to Know to Stay Ahead?",
    text: "Nunc nulla vestibulum nunc quam arcu tristique convallis. Posuere augue pellentesque mauris gravida",
  },
  {
    id: 22,
    img: "./image/blog/post2.png",
    alt: "colorful cubes with pictures are on the keyboard",
    category: 2,
    date: "06.02.2017",
    autor: "By Shawn Edwards",
    title: "How to Evaluate and Compare Social Media Tools Today.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 23,
    img: "./image/blog/post3.png",
    alt: "cubes with arrows",
    category: 4,
    date: "01.02.2017",
    autor: "By Shawn Edwards",
    title: "The Best Practices to Optimize Your Website for Mobile.",
    text: "Pharetra, ullamcorper iaculis viverra parturient sed id sed. Convallis proin dignissim lacus, purus gravida",
  },
  {
    id: 24,
    img: "./image/blog/post4.png",
    alt: "the index finger points to the search bar",
    category: 5,
    date: "25.01.2017",
    autor: "By Diane Mccoy",
    title: "10 Seriously Underused Paid Search Strategies.",
    text: "Euismod congue faucibus diam etiam diam netus vitae ornare vitae. Cursus sollicitudin posuere venenatis",
  },
  {
    id: 25,
    img: "./image/blog/post5.png",
    alt: "an open book with an inscription -  Content is King",
    category: 1,
    date: "23.01.2017",
    autor: "By Shawn Edwards",
    title: "How to Create Content That Gets Linked and Shared.",
    text: "Eu donec pellentesque et aliquet. Fringilla morbi etiam turpis nisl nunc, quis sagittis ut. Pulvinar amet vitae",
  },
  {
    id: 26,
    img: "./image/blog/post6.png",
    alt: "a head from which light bulbs fly up",
    category: 2,
    date: "18.01.2017",
    autor: "By Jane Cooper",
    title: "12 Simple Tips to Creating an Effective Ad.",
    text: "Imperdiet risus consectetur dignissim lorem sollicitudin eget bibendum pellentesque nec. Adipiscing viverra in non euismod. Amet nulla aliquam nulla magna",
  },
];

export const postsCategories: ICategory[] = [
  {
    id: 0,
    name: "All",
  },
  {
    id: 1,
    name: "Media & Press",
  },
  {
    id: 2,
    name: "Ad Tips",
  },
  {
    id: 3,
    name: "Marketing",
  },
  {
    id: 4,
    name: "SEO",
  },
  {
    id: 5,
    name: "Paid Search",
  },
];

export const postsTrend = [
  {
    id: 1,
    image: "./image/blog/trend-post1.png",
    alt: "white keyboard and mouse",
    date: "05.07.2020",
    title: "5 Surprising Ways to Combine Content Marketing with PPC",
  },
  {
    id: 2,
    image: "./image/blog/trend-post2.png",
    alt: "white keyboard and black tablet on a yellow background",
    date: "09.04.2020",
    title: "Why SEO Is All About Content Marketing?",
  },
  {
    id: 3,
    image: "./image/blog/trend-post3.png",
    alt: "robot arm with lemon",
    date: "12.03.2020",
    title: "10 tips for a small business digital marketing strategy",
  },
];

export const tags = [
  {
    id: 1,
    name: "tips&tricks",
  },
  {
    id: 2,
    name: "strategy",
  },
  {
    id: 3,
    name: "SMM",
  },
  {
    id: 4,
    name: "business",
  },
  {
    id: 5,
    name: "PPC",
  },
  {
    id: 6,
    name: "targeting",
  },
];

//ServiceItemPage
export const serviceInfo = [
  {
    id: 1,
    img: "./image/services-item/info-first.png",
    imgalt: "graphics on a tablet",
    title: "We go above and beyond to ensure successful SEO",
    text: "Lacus ac mollis vitae viverra. Tincidunt est, feugiat montes, viverra ullamcorper mi dui, nulla pharetra. Sapien urna nullam elit diam mauris orci. Volutpat quam tempus justo, aliquam. Tortor ultrices mattis eget orci eu nisi sed augue odio. Et senectus risus, pharetra, tristique libero. Dolor risus ac quam dictum mattis ultrices laoreet sapien. Feugiat lacus, suscipit eu sociis et quis  hendrerit. Cras at ac magna ultricies orci.",
  },
  {
    id: 2,
    img: "./image/blog/latest-post1.png",
    imgalt: "someone is writing something in a notebook",
    title: "Search Engine Optimization",
    text: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, molestiae odio? Repellendus aspernatur ducimus, reprehenderit quo aut soluta architecto dolorem odit minus quidem nemo modi earum at maxime, voluptas quam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, molestiae odio? Repellendus aspernatur ducimus, reprehenderit quo aut soluta architecto dolorem odit minus quidem nemo modi earum at maxime.",
  },
  {
    id: 3,
    img: "./image/blog/latest-post2.png",
    imgalt: "a hand with a pen on a diagram",
    title: "Research Service",
    text: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut obcaecati dignissimos similique iste! Maiores dolores eaque fugiat fugit a? Aut similique velit unde, incidunt iusto ipsa? Ipsam itaque architecto repellat! Facilis voluptas mollitia error praesentium porro? Soluta beatae, in sapiente ipsum quo molestiae recusandae totam commodi dolores exercitationem odit quibusdam optio cupiditate iusto illo qui? Eius voluptas aspernatur dolore quas.",
  },
  {
    id: 4,
    img: "./image/blog/post1.png",
    imgalt: "three-dimensional multi-colored parts of a pie chart",
    title: "Content & PR Service",
    text: "Nisi quibusdam facilis aperiam eveniet similique nobis voluptatem, consectetur ipsum porro repudiandae neque, quae inventore officia perferendis. Necessitatibus laboriosam dolorem enim quod fugiat at, velit eligendi eum!         Quibusdam natus quo ea laboriosam porro fuga explicabo suscipit adipisci dolorum, voluptatum velit eaque in dolores inventore id corporis blanditiis ullam fugiat aperiam quidem, laborum ducimus laudantium repudiandae? Earum, excepturi!          Animi eum laborum laboriosam quidem ex expedita perferendis.",
  },
];

export const seoCards = [
  {
    id: 1,
    img: "./image/services-item/ic-options.svg",
    alt: "options icon",
    title: "SEO Strategy",
    text: "Culpa nostrud commodo ea consequat aliquip reprehenderit. Veniam velit nostrud aliquip sunt.",
  },
  {
    id: 2,
    img: "./image/services-item/ic-analytics.svg",
    alt: "analysis icon",
    title: "Competitor Analysis",
    text: "Culpa nostrud commodo ea consequat aliquip reprehenderit. Veniam velit nostrud aliquip sunt.",
  },
  {
    id: 3,
    img: "./image/services-item/ic-target.svg",
    alt: "target icon",
    title: "Technical Audit",
    text: "Congue viverra in quis urna lectus proin massa. Aliquam, justo nisl sed diam nibh vehicula.",
  },
  {
    id: 4,
    img: "./image/services-item/ic-chart.svg",
    alt: "chart icon",
    title: "Content Strategy",
    text: "Posuere sed quam etiam semper id id euismod. Feugiat cras donec elementum interdum in.",
  },
  {
    id: 5,
    img: "./image/services-item/ic-speaker.svg",
    alt: "speaker icon",
    title: "Media Promotion",
    text: "Aliquam turpis viverra quam sit interdum blandit posuere pellentesque. Nisl, imperdiet gravida massa neque.",
  },
  {
    id: 6,
    img: "./image/services-item/ic-analysis.svg",
    alt: "analisys icon",
    title: "SEO Reports",
    text: "Congue phasellus est, amet sem bibendum sollicitudin arcu scelerisque senectus. Mauris, mus tincidunt a, nisi.",
  },
];
